const INNER_RADIUS = 10;
const HEX_SIZE = 15;

const OUTER_RADIUS = 30;
const TRAIL_SPEED = 0.15;
const DIAMOND_SPACE = 15;
const CHEV_GAP = 5; //DIAMOND_SPACE / 2;

export {
	CHEV_GAP,
	DIAMOND_SPACE,
	HEX_SIZE,
	INNER_RADIUS,
	OUTER_RADIUS,
	TRAIL_SPEED,
};
